apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-mock
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: vllm-container
        # Deliberately overriding the command to break the web server
        command: ["/bin/sh", "-c", "sleep 3600"]
