apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-memory-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # <-- Execute this first
spec:
  selector:
    matchLabels:
      app: vector-memory-db
  template:
    metadata:
      labels:
        app: vector-memory-db
    spec:
      containers:
      - name: redis
        image: redis:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: vector-memory-db-svc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: vector-memory-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
